name: Inject configs
description: Injects configs required for application to run

runs:
  using: 'composite'
  steps:
    - uses: bluwy/substitute-string-action@v3
      id: configure-wombat-api
      with:
        _input-file: 'src-tauri/src/main.rs'
        _output-file: 'src-tauri/src/main.rs'
        _format-key: '%%key%%'
        PROFILE: 'release'
        WOMBAT_API_URL: ${{ secrets.WOMBAT_API_URL }}
        WOMBAT_API_USER: ${{ secrets.WOMBAT_API_USER }}
        WOMBAT_API_PASSWORD: ${{ secrets.WOMBAT_API_PASSWORD }}
