// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v4.24.4
// source: proto/arh.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Environment int32

const (
	Environment_UNKNOWN Environment = 0
	Environment_DEV     Environment = 1
	Environment_DEMO    Environment = 2
	Environment_PROD    Environment = 3
)

// Enum value maps for Environment.
var (
	Environment_name = map[int32]string{
		0: "UNKNOWN",
		1: "DEV",
		2: "DEMO",
		3: "PROD",
	}
	Environment_value = map[string]int32{
		"UNKNOWN": 0,
		"DEV":     1,
		"DEMO":    2,
		"PROD":    3,
	}
)

func (x Environment) Enum() *Environment {
	p := new(Environment)
	*p = x
	return p
}

func (x Environment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Environment) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_arh_proto_enumTypes[0].Descriptor()
}

func (Environment) Type() protoreflect.EnumType {
	return &file_proto_arh_proto_enumTypes[0]
}

func (x Environment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Environment.Descriptor instead.
func (Environment) EnumDescriptor() ([]byte, []int) {
	return file_proto_arh_proto_rawDescGZIP(), []int{0}
}

type DescribeBastionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeBastionsRequest) Reset() {
	*x = DescribeBastionsRequest{}
	mi := &file_proto_arh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeBastionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeBastionsRequest) ProtoMessage() {}

func (x *DescribeBastionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeBastionsRequest.ProtoReflect.Descriptor instead.
func (*DescribeBastionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_arh_proto_rawDescGZIP(), []int{0}
}

func (x *DescribeBastionsRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type DescribeBastionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*BastionInstance     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeBastionsResponse) Reset() {
	*x = DescribeBastionsResponse{}
	mi := &file_proto_arh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeBastionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeBastionsResponse) ProtoMessage() {}

func (x *DescribeBastionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeBastionsResponse.ProtoReflect.Descriptor instead.
func (*DescribeBastionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_arh_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeBastionsResponse) GetResults() []*BastionInstance {
	if x != nil {
		return x.Results
	}
	return nil
}

type BastionInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Env           Environment            `protobuf:"varint,2,opt,name=env,proto3,enum=arh.Environment" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BastionInstance) Reset() {
	*x = BastionInstance{}
	mi := &file_proto_arh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BastionInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BastionInstance) ProtoMessage() {}

func (x *BastionInstance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BastionInstance.ProtoReflect.Descriptor instead.
func (*BastionInstance) Descriptor() ([]byte, []int) {
	return file_proto_arh_proto_rawDescGZIP(), []int{2}
}

func (x *BastionInstance) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *BastionInstance) GetEnv() Environment {
	if x != nil {
		return x.Env
	}
	return Environment_UNKNOWN
}

var File_proto_arh_proto protoreflect.FileDescriptor

var file_proto_arh_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x72, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x61, 0x72, 0x68, 0x22, 0x33, 0x0a, 0x17, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x42, 0x61, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x4a, 0x0a, 0x18, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x42, 0x61, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x72, 0x68, 0x2e, 0x42,
	0x61, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x56, 0x0a, 0x0f, 0x42, 0x61, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x03, 0x65,
	0x6e, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x61, 0x72, 0x68, 0x2e, 0x45,
	0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x03, 0x65, 0x6e, 0x76, 0x2a,
	0x37, 0x0a, 0x0b, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x44,
	0x45, 0x56, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x45, 0x4d, 0x4f, 0x10, 0x02, 0x12, 0x08,
	0x0a, 0x04, 0x50, 0x52, 0x4f, 0x44, 0x10, 0x03, 0x32, 0x58, 0x0a, 0x03, 0x41, 0x72, 0x68, 0x12,
	0x51, 0x0a, 0x10, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x42, 0x61, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x2e, 0x61, 0x72, 0x68, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x42, 0x61, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x72, 0x68, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x42, 0x61, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x64, 0x77, 0x69, 0x6c, 0x6b, 0x6f, 0x6c, 0x65, 0x6b, 0x2f, 0x77, 0x6f, 0x6d, 0x62, 0x61,
	0x74, 0x2f, 0x61, 0x72, 0x68, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_arh_proto_rawDescOnce sync.Once
	file_proto_arh_proto_rawDescData = file_proto_arh_proto_rawDesc
)

func file_proto_arh_proto_rawDescGZIP() []byte {
	file_proto_arh_proto_rawDescOnce.Do(func() {
		file_proto_arh_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_arh_proto_rawDescData)
	})
	return file_proto_arh_proto_rawDescData
}

var file_proto_arh_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_arh_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_arh_proto_goTypes = []any{
	(Environment)(0),                 // 0: arh.Environment
	(*DescribeBastionsRequest)(nil),  // 1: arh.DescribeBastionsRequest
	(*DescribeBastionsResponse)(nil), // 2: arh.DescribeBastionsResponse
	(*BastionInstance)(nil),          // 3: arh.BastionInstance
}
var file_proto_arh_proto_depIdxs = []int32{
	3, // 0: arh.DescribeBastionsResponse.results:type_name -> arh.BastionInstance
	0, // 1: arh.BastionInstance.env:type_name -> arh.Environment
	1, // 2: arh.Arh.DescribeBastions:input_type -> arh.DescribeBastionsRequest
	2, // 3: arh.Arh.DescribeBastions:output_type -> arh.DescribeBastionsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_arh_proto_init() }
func file_proto_arh_proto_init() {
	if File_proto_arh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_arh_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_arh_proto_goTypes,
		DependencyIndexes: file_proto_arh_proto_depIdxs,
		EnumInfos:         file_proto_arh_proto_enumTypes,
		MessageInfos:      file_proto_arh_proto_msgTypes,
	}.Build()
	File_proto_arh_proto = out.File
	file_proto_arh_proto_rawDesc = nil
	file_proto_arh_proto_goTypes = nil
	file_proto_arh_proto_depIdxs = nil
}
