// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.4
// source: proto/arh.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Arh_DescribeBastions_FullMethodName = "/arh.Arh/DescribeBastions"
)

// ArhClient is the client API for Arh service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArhClient interface {
	// Sends a greeting
	DescribeBastions(ctx context.Context, in *DescribeBastionsRequest, opts ...grpc.CallOption) (*DescribeBastionsResponse, error)
}

type arhClient struct {
	cc grpc.ClientConnInterface
}

func NewArhClient(cc grpc.ClientConnInterface) ArhClient {
	return &arhClient{cc}
}

func (c *arhClient) DescribeBastions(ctx context.Context, in *DescribeBastionsRequest, opts ...grpc.CallOption) (*DescribeBastionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeBastionsResponse)
	err := c.cc.Invoke(ctx, Arh_DescribeBastions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArhServer is the server API for Arh service.
// All implementations must embed UnimplementedArhServer
// for forward compatibility.
type ArhServer interface {
	// Sends a greeting
	DescribeBastions(context.Context, *DescribeBastionsRequest) (*DescribeBastionsResponse, error)
	mustEmbedUnimplementedArhServer()
}

// UnimplementedArhServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArhServer struct{}

func (UnimplementedArhServer) DescribeBastions(context.Context, *DescribeBastionsRequest) (*DescribeBastionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeBastions not implemented")
}
func (UnimplementedArhServer) mustEmbedUnimplementedArhServer() {}
func (UnimplementedArhServer) testEmbeddedByValue()             {}

// UnsafeArhServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArhServer will
// result in compilation errors.
type UnsafeArhServer interface {
	mustEmbedUnimplementedArhServer()
}

func RegisterArhServer(s grpc.ServiceRegistrar, srv ArhServer) {
	// If the following call pancis, it indicates UnimplementedArhServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Arh_ServiceDesc, srv)
}

func _Arh_DescribeBastions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeBastionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArhServer).DescribeBastions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Arh_DescribeBastions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArhServer).DescribeBastions(ctx, req.(*DescribeBastionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Arh_ServiceDesc is the grpc.ServiceDesc for Arh service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Arh_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arh.Arh",
	HandlerType: (*ArhServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DescribeBastions",
			Handler:    _Arh_DescribeBastions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/arh.proto",
}
