name: 'nix-pr_check'
on: [pull_request]

jobs:
  test-tauri:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v4
      - uses: bluwy/substitute-string-action@v3
        id: sub
        with:
          _input-file: 'src-tauri/src/main.rs'
          _output-file: 'src-tauri/src/main.rs'
          _format-key: '%%key%%'
          PROFILE: 'release'
          WOMBAT_API_URL: ${{ secrets.WOMBAT_API_URL }}
          WOMBAT_API_USER: ${{ secrets.WOMBAT_API_USER }}
          WOMBAT_API_PASSWORD: ${{ secrets.WOMBAT_API_PASSWORD }}
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-build
      - run: nix-shell --run "echo OK"
      - name: Archive executable
        uses: actions/upload-artifact@v4
        with:
          name: nix-thing
          path: |
            src-tauri/target/release/bundle
            src-tauri/target/release/**/Wombat*
            src-tauri/target/universal-apple-darwin/**/release/**/Wombat*
