name: 'pr_check'
on: [pull_request]

jobs:
  test-tauri:
    if: github.head_ref != 'release-please--branches--main'
    strategy:
      fail-fast: false
      matrix:
        include:
          # - platform: 'macos-latest' # for Arm based macs (M1 and above).
          #   args: '--verbose --target aarch64-apple-darwin'
          #   platform-name: 'Macos-M1'
          # - platform: 'macos-latest' # for Intel based macs.
          #   args: '--verbose --target x86_64-apple-darwin'
          #   platform-name: 'Macos-Intel'
          - platform: 'macos-latest' # for Univrsal based macs.
            args: '--verbose --target universal-apple-darwin'
            platform-name: 'Macos-Universal'
          - platform: 'ubuntu-latest' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: '--verbose'
            platform-name: 'Linux'
          - platform: 'windows-latest'
            args: '--verbose'
            platform-name: 'Windows'
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v4
      - uses: bluwy/substitute-string-action@v3
        id: sub
        with:
          _input-file: 'src-tauri/src/main.rs'
          _output-file: 'src-tauri/src/main.rs'
          _format-key: '%%key%%'
          PROFILE: 'release'
          WOMBAT_API_URL: ${{ secrets.WOMBAT_API_URL }}
          WOMBAT_API_USER: ${{ secrets.WOMBAT_API_USER }}
          WOMBAT_API_PASSWORD: ${{ secrets.WOMBAT_API_PASSWORD }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      - name: install frontend dependencies
        run: pnpm install --frozen-lockfile
      - name: lint
        run: |
          pnpm lint
          pnpm check
      - uses: tauri-apps/tauri-action@v0
        env:
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ matrix.args }}
      - name: Archive executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.platform-name}}-${{ matrix.platform }}-${{ github.sha }}
          path: |
            src-tauri/target/release/bundle
            src-tauri/target/release/**/Wombat*
            src-tauri/target/universal-apple-darwin/**/release/**/Wombat*
