name: 'pr_check'
on: [pull_request]

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest, ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: bluwy/substitute-string-action@v1
        id: sub
        with:
          _input-file: 'src-tauri/src/main.rs'
          _output-file: 'src-tauri/src/main.rs'
          _format-key: '%%key%%'
          PROFILE: 'release'
          AXIOM_TOKEN: ${{ secrets.AXIOM_TOKEN }}
          AXIOM_ORG: ${{ secrets.AXIOM_ORG }}
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
          TURSO_SYNC_URL: ${{ secrets.TURSO_SYNC_URL }}
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf glib-2.0
      - name: install frontend dependencies
        run: npm ci
      - uses: tauri-apps/tauri-action@v0
        env:
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-${{ github.sha }}
          path: |
            src-tauri/target/release/bundle
            src-tauri/target/release/bundle/Wombat*
