name: 'trigger-release'
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'x.x.x or x.x.x-alpha'
        required: true

jobs:
  trigger-release:
    permissions:
      contents: write
      pull-requests: write
      actions: write
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
      - name: install frontend dependencies
        run: npm ci
      - name: Configure git
        run: |
          git config --global user.name 'dwilkolek'
          git config --global user.email 'dwilkolek@users.noreply.github.com'
      - name: bump version and open pr
        run: |
          npm run bump-version ${{ inputs.version }} true
          gh pr create -B main -H release-v${{ inputs.version }} --title 'Release v${{ inputs.version }}' --body 'Created by Github action'
          gh pr merge release-v${{ inputs.version }} --auto --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
