name: Update dependencies
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global user.name dwilkolek-ghbot
          git config --global user.email dwilkolek-ghbot@users.noreply.github.com
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          token: ${{ steps.app-token.outputs.token }}
      - uses: './.github/actions/prepare-build-env'
      - name: update frontend dependencies
        run: |
          pnpm up --latest
      - name: update update server dependencies
        run: |
          cd update-server
          pnpm up --latest
          cd ..
      - name: update tauri dependencies
        run: |
          cd src-tauri
          cargo install cargo-edit
          cargo upgrade
          cd ..
      - name: commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          diff=$(git status --porcelain)
          if [ -z "$diff" ]; then
            echo "No changes to commit"
            exit 0
          fi

          git checkout -b "update-dependencies-$(date '+%Y-%m-%d')"
          git add .
          git commit -m "chore: update dependencies $(date '+%Y-%m-%d')"
          git push -f origin "update-dependencies-$(date '+%Y-%m-%d')"
          gh pr create -B base_branch -H "update-dependencies-$(date '+%Y-%m-%d')" --title "Update dependencies $(date '+%Y-%m-%d')" --body 'Created by Github action'
